language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: true
node_js:
  - '9'
  - '8'
before_script:
  - npm prune
after_success:
  - npm run coverage:report
  - npm run travis-deploy-once "npm run semantic-release"
script:
  - npm run validate
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
