language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - '9'
  - '8'
before_script:
  - npm prune
after_success:
  - npm run coverage:report
  - npm run semantic-release
script:
  - npm run coverage
  - npm run coverage:check
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
